version: '3'
services:
  web:
    build: .
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://username:password@db:5432/dbname
    depends_on:
      - db
    # Using docker compose watch will sync any update you make in app
    # watch isn't working have to disable pycache
    # develop:
    #   watch:
    #   - path: ./app
    #     target: /var/www/app
    #     action: sync
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"

# version: '3'
# services:
#   web:
#     build: .
#     environment:
#       - FLASK_APP=app
#       - SCHEMA=mydb
#       - FLASK_ENV=development
#       # - FLASK_ENV=produciton
#       # - FLASK_DEBUG=true
#       - DATABASE_URL=postgresql://username:password@db:5432/dbname
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"
#     #This works, but it's pointless since we still have to send a request
#     #to our server to see an update via a response.  But it does work.
#     develop:
#       watch:
#       - path: ./react-vite/dist
#         target: /var/www/react-vite/dist/
#         action: sync

#   db:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_USER=username
#       - POSTGRES_DB=dbname
#     ports:
#       - "5432:5432"


# This works, but it's pointless since we still have to send a request
# to our server to see an update via a response.  But it does work.
  # frontend:
  #   build: ./react-vite
  #   depends_on:
  #     - web
  #   ports:
  #     - "3000:3000"
  #   develop:
  #     watch:
  #       - path: ./react-vite/dist
  #         target: /react-vite/dist
  #         action: sync
