services:
- type: web
  name: flask-app
  # env: python
  env: docker
  plan: free
  region: ohio
  # buildCommand: <your-build-command>  # e.g., pip install -r requirements.txt
  # startCommand: gunicorn app:app
  envVars:
    - key: FLASK_ENV
      value: production
    - key: FLASK_APP
      value: app
    - key: DATABASE_URL
      fromDatabase:
        name: dbname
        property: connectionString
    - key: SCHEMA
      value: demo_app
    - key: SECRET_KEY
      generateValue: true
  # healthCheckPath: /health

databases:
- name: dbname
  plan: free
  region: ohio
  # type: postgres
  # version: 15
