# name: Main Branch CI

# # this runs on any pr to main and subsequent commit to that branch
# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - ready_for_review
#       - labeled
#       - unlabeled
#       - edited
#       - synchronize
#     branches:
#       - 'main'

# # this runs when something is pushed to the main branch
# # on:
# #   push:
# #     branches:
# #       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: password
#           POSTGRES_USER: username
#           POSTGRES_DB: dbname
#         ports:
#           - 5432:5432
#         # Set health checks to wait until postgres is ready
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v4

#     # Set up Python environment
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.11'

#     # Install dependencies
#     - name: Install dependencies
#       run: |
#         pip install --no-cache-dir -r requirements.txt
#         pip install --no-cache-dir psycopg2

#     # Run your migrations and seeding
#     - name: Run migrations and seed database
#       env:
#         FLASK_APP: app
#         SCHEMA: mydb
#         FLASK_ENV: production
#         DATABASE_URL: postgresql://username:password@localhost:5432/dbname
#       run: |
#         flask db upgrade
#         flask seed all

#     # Additional steps such as running tests can be added here


# THIS VERSION WORKS:
# name: Main Branch CI

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - ready_for_review
#       - labeled
#       - unlabeled
#       - edited
#       - synchronize
#     branches:
#       - 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: password
#           POSTGRES_USER: username
#           POSTGRES_DB: dbname
#         ports:
#           - 5432:5432
#         # Set health checks to wait until postgres is ready
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v4

#     # Set up Python environment
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.9'

#     # Cache Python dependencies
#     - name: Cache Python dependencies
#       uses: actions/cache@v3
#       with:
#         path: ~/.cache/pip
#         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#         restore-keys: |
#           ${{ runner.os }}-pip-

#     # Install dependencies
#     - name: Install dependencies
#       run: |
#         pip install -r requirements.txt
#         pip install psycopg2

#     # Run your migrations and seeding
#     - name: Run migrations and seed database
#       env:
#         FLASK_APP: app
#         SCHEMA: mydb
#         FLASK_ENV: production
#         DATABASE_URL: postgresql://username:password@localhost:5432/dbname
#       run: |
#         flask db upgrade
#         flask seed all


# If there is an issue with mac users, we may need the matrix strategy
# taken from here https://github.com/actions/cache/blob/main/examples.md#python---pip
# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#         include:
#         - os: ubuntu-latest
#           path: ~/.cache/pip
#         - os: macos-latest
#           path: ~/Library/Caches/pip
#         - os: windows-latest
#           path: ~\AppData\Local\pip\Cache
#     steps:
#     - uses: actions/cache@v3
#       with:
#         path: ${{ matrix.path }}
#         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#         restore-keys: |
#          ${{ runner.os }}-pip-


# NEW VERSION TO IMPROVE SPEED:
name: Main Branch CI

# This is what triggers the action
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - labeled
      - unlabeled
      - edited
      - synchronize
    branches:
      - 'main'

jobs:
  build-and-test-migrations-and-seeds:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
        # these could be moved to secrets, but they're dummy values
          POSTGRES_PASSWORD: password
          POSTGRES_USER: username
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
      # this is Render's default version of python
      # https://render.com/docs/python-version#:~:text=Python%20version%203.11.,Python%20version%20(e.g.%2C%203.9.
        python-version: '3.11'

    # Cache Python dependencies
    # https://github.com/actions/cache/blob/main/caching-strategies.md
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install psycopg2


    - name: Run migrations and seed database
      env:
      # these could be moved to secrets, but they're dummy values anyway
        FLASK_APP: app
        SCHEMA: mydb
        FLASK_ENV: production
        DATABASE_URL: postgresql://username:password@localhost:5432/dbname
      run: |
        flask db upgrade
        flask seed all

    # Add additional steps for testing, linting, etc.
